### ISSUE TITLE
Link to single message does not work

### ISSUE THREAD

**Issue by ernestpeter** [NetConsultAG/netc_nsb#12]
In the list of messages, when i click on the title / link of a message, I get error _Does not work: Unknow news message medienmitteilungen.msg-id-57213.html_
see for example your list http://dev.kommission.netconsult.ch/index.php?id=48

**Comment by nitsan-technologies** [comment]
Hi,

There is change in link tag retrieved from feed. So it was giving error. We have adapt it. 
This is solved now.

Thanks!

**Comment by ernestpeter** [comment]
Sorry I still get error message 
_Unknow news message medienmitteilungen.msg-id-_
in http://dev.kommission.netconsult.ch/index.php?id=181
It's not a cache problem as far as I see

**Comment by ernestpeter** [comment]
After publication on dev.kommissionen ist worked.
Sorry for the misinformation.
Thanks!
