### ISSUE TITLE
Documents ANDLinks missing

### ISSUE THREAD

**Issue by ernestpeter** [NetConsultAG/netc_nsb#8]
If a message has only links or only documents these are shown.
If a message has both, like for message 61668 then neither links nor documents are shown
See http://dev.kommission.netconsult.ch/index.php?id=180

**Comment by nitsan-technologies** [comment]
Hi,

It is solved. 
**Note :** It will show only when <attachement> and <link> has <position>Context</position> as you said http://prntscr.com/bv83zu. Please see http://prntscr.com/bv84ft

Thanks!

**Comment by ernestpeter** [comment]
Not solved yet.
Does not include documents and links in HTML Code for message 61668 (see http://kommission.netconsult.ch/index.php?id=194)

**Comment by nitsan-technologies** [comment]
Hi,

As per i said It will show only when and has <position>Context</position>as you said in specification http://prntscr.com/bv83zu. Please see http://prntscr.com/bv84ft

But message 61668 has <position>Content</position> in it. So It will not show. check it here also https://www.news-service.admin.ch/NSBSubscriber/messages?msg-id=61668

Thanks!

**Comment by ernestpeter** [comment]
Yes, you are right.
But he interface specifications for www.news.admin.ch seem to be wrong in this case or I got them wrong. 
Please correct my specifications  (see http://prnt.sc/c20022) and do not check for <position> in links and attachments.
Thanks.

**Comment by nitsan-technologies** [comment]
Hi,

Okay, We have removed condition for links and attachment. Please check it at your end and let us know.

Thanks!

**Comment by ernestpeter** [comment]
Works now.
Thanks
